### ISSUE TITLE
Filtered items can't be purchased sometimes

### ISSUE THREAD

**Issue by DJScias** [TheKrowi/Krowi_ExtendedVendorUI#16]
Hello there,

I alluded to this back here: https://github.com/TheKrowi/Krowi_ExtendedVendorUI/issues/1#issuecomment-1739378815

Initially with my checks things seemed to work now. Shift-click was back in order and filtering stuff did seem to make me able to buy stuff once more.

However it seems the bug still persists in some ways, and maybe it's related to this not being gold but another currency? I don't know. But I made a GIF about it as requested.
![Wow_zyzSpnle1e](https://github.com/TheKrowi/Krowi_ExtendedVendorUI/assets/439655/e04b7a6e-a826-4fac-8490-300e80efffd3)
(Clicking on the gif to its own page makes it look better, apparently otherwise it's a bit blocky.)

**What happens?**
Once I filter it on mounts, I can't seem to buy the mount. Once I remove the filter, it all works like normal.

There's no error message, no anything. It just doesn't make the actual purchase when the filter is applied.

**Comment by TheKrowi** [comment]
Should be fixed in https://github.com/TheKrowi/Krowi_ExtendedVendorUI/releases/tag/6.0-beta7
