### ISSUE TITLE
Feature Request : Auto sell junk / Auto repair

### ISSUE THREAD

**Issue by Cofibib** [TheKrowi/Krowi_ExtendedVendorUI#31]
Hi,

Found your addons searching for a replacement to "Vendorer" which is not maintained and your addon work like a charm regarding extension of the vendor frame (even more better since we can configure number of Rows/Columns).
But I miss the option to auto sell junk items and to auto repair (maybe with choice to enable or not the guild bank repair).
I'm used to have it done automatically would be great to have it here.

Thanks.

**Comment by TheKrowi** [comment]
Have a look here: https://github.com/TheKrowi/Krowi_Vendorer/releases/tag/0.10. This is a side project but not officially supported yet for the public.

**Comment by Cofibib** [comment]
> Have a look here: https://github.com/TheKrowi/Krowi_Vendorer/releases/tag/0.10. This is a side project but not officially supported yet for the public.

Seems promising ! Right now the button display "sell 12 items" where only two was show in the list so I don't take the risk to clique 😆 and not sure the rules enable/disable is saved on reload. But it's exactly what I need so I will follow it ans wait the official release on curse !
Thank you.
