### ISSUE TITLE
Bug doesnt work properly

### ISSUE THREAD

**Issue by Addonman** [TheKrowi/Krowi_ExtendedVendorUI#41]
I updated addon to 8.3,installed,reinstalled.Simply i don't see vendor ui extended.

**Comment by Sneed-Daytona** [comment]
> I updated addon to 8.3,installed,reinstalled.Simply i don't see vendor ui extended.

This happened to me too. The culprit was the addon "BuyEmAll" for me. I disabled it and now the addon is working.

**Comment by Addonman** [comment]
I have seen it now on discord. And also can confirm it.
