### ISSUE TITLE
multiple bugs. 1st to happen: GetAddonMetadata

### ISSUE THREAD

**Issue by Runisco** [TheKrowi/Krowi_ExtendedVendorUI#44]
4x ...endedVendorUI/Libs/Krowi_Util/Krowi_Metadata-1.0.lua:25: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@Krowi_ExtendedVendorUI/Libs/Krowi_Util/Krowi_Metadata-1.0.lua"]:25: in function `GetAddOnMetadata'
[string "@Krowi_ExtendedVendorUI/Libs/Libs.lua"]:11: in main chunk

Locals:
addonName = "Krowi_ExtendedVendorUI"
(*temporary) = nil
(*temporary) = "Krowi_ExtendedVendorUI"
(*temporary) = "Title"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"

**Comment by TheKrowi** [comment]
This should not be happening, have you updated all the addons?

**Comment by Runisco** [comment]
It's fixed now, was an issue when I made it.
