### ISSUE TITLE
bug vendor in tanaris

### ISSUE THREAD

**Issue by Addonman** [TheKrowi/Krowi_ExtendedVendorUI#45]
I bought some stuff on vendor from 20th anniversary event .Now tooltip is messed up. It shows ,since i bought like 3 items,  tool tip from item that 3 places to the right of item i am pointing cursor at.

**Comment by Addonman** [comment]
![1](https://github.com/user-attachments/assets/223a47dd-fce4-4392-96da-e2a0fa3131a3)

**Comment by NoShotz** [comment]
This bug happens in basically all vendors, it seems to happen when a vendor item is hidden.

**Comment by AbelardTullus** [comment]
Been having this issue too.

**Comment by TheKrowi** [comment]
Disabling the hide filters for now resolves the issue.
