### ISSUE TITLE
Reopen:  Interacting with a vendor prints all purchaseable item IDs in chat #49 

### ISSUE THREAD

**Issue by Odysseas68** [TheKrowi/Krowi_ExtendedVendorUI#50]
i don't know how can i reopen an issue (i don't think i can) so i link it here:

https://github.com/TheKrowi/Krowi_ExtendedVendorUI/issues/49#issuecomment-2558233768

**Comment by TheKrowi** [comment]
Reason not to open old tickets is cause this is a new bug. Odd thing is though that it does not happen on my client O.o
